name: midnabot

on:
  push:
    branches:
      - master

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:

      - name: Set up source
        uses: actions/checkout@v2

      - name: Set up version
        id: version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            --username ${{ secrets.DOCKER_USERNAME }} \
            --password-stdin ${{ secrets.DOCKER_REPOSITORY }}

      - name: Docker build and push
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --tag ${{ secrets.DOCKER_REPOSITORY }}/midnabot:${{ steps.version.outputs.current-version }} \
            --build-arg SERVICE_PORT=${{ secrets.SERVICE_PORT }} \
            --push .

