name: midnabot

on:
  push:
    branches:
      - midnacoin


jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:

      - name: Setup source
        uses: actions/checkout@v2

      - name: Setup version
        id: version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ secrets.DOCKER_REPOSITORY }}

      - name: Docker build
        run: docker build --tag ${{ secrets.DOCKER_REPOSITORY }}/midnabot:${{ steps.version.outputs.current-version }} .

      - name: Docker push
        run: docker push ${{ secrets.DOCKER_REPOSITORY }}/midnabot:${{ steps.version.outputs.current-version }}
